/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Chat;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.UIManager;

/**
 *
 * @author Wildan
 */
public class ClientForm extends javax.swing.JFrame {

    public SocketClient client;
    public int port;
    public String serverAddr, username, password;
    public Thread clientThread;
    public DefaultListModel model;
    public File file;
    public String historyFile = "D:/History.xml";

    /**
     * Creates new form ClientForm
     */
    public ClientForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Chat Client "+userName.getText());
        model.addElement("All");
        jList1.setSelectedIndex(0);

        clientDisp.setEditable(false);

        this.addWindowListener(new WindowListener() {

            @Override
            public void windowOpened(WindowEvent e) {
            }

            @Override
            public void windowClosing(WindowEvent e) {
                try {
                    client.send(new Pesan("message", username, ".bye", "SERVER"));
                    clientThread.stop();
                } catch (Exception ex) {
                }
            }

            @Override
            public void windowClosed(WindowEvent e) {
            }

            @Override
            public void windowIconified(WindowEvent e) {
            }

            @Override
            public void windowDeiconified(WindowEvent e) {
            }

            @Override
            public void windowActivated(WindowEvent e) {
            }

            @Override
            public void windowDeactivated(WindowEvent e) {
            }
        });
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbl_konek = new javax.swing.JLabel();
        tbl_kirim = new javax.swing.JLabel();
        hostField = new javax.swing.JTextField();
        portField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientDisp = new javax.swing.JTextArea();
        inputClient = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        userName = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(651, 438));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_konek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_konekMouseClicked(evt);
            }
        });
        getContentPane().add(tbl_konek, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 190, 70));

        tbl_kirim.setToolTipText("");
        tbl_kirim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_kirimMouseClicked(evt);
            }
        });
        getContentPane().add(tbl_kirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 570, 190, 80));

        hostField.setText("192.168.0.0");
        hostField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostFieldActionPerformed(evt);
            }
        });
        getContentPane().add(hostField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 105, 220, -1));

        portField.setText("13000");
        portField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portFieldActionPerformed(evt);
            }
        });
        getContentPane().add(portField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 128, 220, -1));

        jScrollPane1.setBorder(null);

        clientDisp.setColumns(20);
        clientDisp.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        clientDisp.setRows(5);
        jScrollPane1.setViewportView(clientDisp);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 178, 720, 380));

        inputClient.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputClient.setBorder(null);
        inputClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputClientKeyPressed(evt);
            }
        });
        getContentPane().add(inputClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 575, 710, 70));

        jScrollPane2.setBorder(null);

        jList1.setModel((model = new DefaultListModel()));
        jScrollPane2.setViewportView(jList1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 190, 330));
        getContentPane().add(userName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 105, 200, -1));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 128, 200, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/layout_client.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hostFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hostFieldActionPerformed

    private void portFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portFieldActionPerformed

    private void tbl_kirimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_kirimMouseClicked
        String msg = inputClient.getText();
        String nama = userName.getText();
        String target = jList1.getSelectedValue().toString();

        if (!msg.isEmpty() && !target.isEmpty()) {
            inputClient.setText("");
            client.send(new Pesan("message", username, msg, target));
        }
    }//GEN-LAST:event_tbl_kirimMouseClicked

    private void tbl_konekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_konekMouseClicked
        serverAddr = hostField.getText();
        port = Integer.parseInt(portField.getText());
        if (!serverAddr.isEmpty() && !portField.getText().isEmpty()) {
            try {
                client = new SocketClient(this);
                clientThread = new Thread(client);
                clientThread.start();
                client.send(new Pesan("test", "testUser", "testContent", "SERVER"));
            } catch (Exception ex) {
                clientDisp.append("[Application > Me] : Server not found\n");
            }
        }
        //--
        username = userName.getText();
        password = jPasswordField1.getText();

        if (!username.isEmpty() && !password.isEmpty()) {
            client.send(new Pesan("signup", username, password, "SERVER"));
        }

    }//GEN-LAST:event_tbl_konekMouseClicked

    private void inputClientKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputClientKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER) {
            String msg = inputClient.getText();
            String nama = userName.getText();
            String target = jList1.getSelectedValue().toString();

            if (!msg.isEmpty() && !target.isEmpty()) {
                inputClient.setText("");
                client.send(new Pesan("message", username, msg, target));
            }
        }
    }//GEN-LAST:event_inputClientKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            System.out.println("Look & Feel exception");
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea clientDisp;
    public javax.swing.JTextField hostField;
    public javax.swing.JTextField inputClient;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JList jList1;
    public javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField portField;
    private javax.swing.JLabel tbl_kirim;
    private javax.swing.JLabel tbl_konek;
    public javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
