/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Chat;

/**
 *
 * @author Irfandi
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        clear_highlight();
        clear_panel();
        panel_server.setVisible(true);
        menu_highlight_server.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_about = new javax.swing.JLabel();
        panel_about = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        panel_client = new javax.swing.JLayeredPane();
        tbl_mode_client = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panel_server = new javax.swing.JLayeredPane();
        tbl_mode_server = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menu_server = new javax.swing.JLabel();
        menu_client = new javax.swing.JLabel();
        menu_highlight_server = new javax.swing.JLabel();
        menu_highlight_client = new javax.swing.JLabel();
        menu_highlight_about = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu_about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu_ebout.png"))); // NOI18N
        menu_about.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_aboutMouseClicked(evt);
            }
        });
        getContentPane().add(menu_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 216, 230, 60));

        panel_about.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PANEL_about.png"))); // NOI18N
        panel_about.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 770, -1));

        getContentPane().add(panel_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 99, 770, 570));

        panel_client.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_mode_client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_mode_clientMouseClicked(evt);
            }
        });
        panel_client.add(tbl_mode_client, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 350, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panel_client.png"))); // NOI18N
        panel_client.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 770, -1));

        getContentPane().add(panel_client, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 99, 770, 570));

        panel_server.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbl_mode_server.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_mode_serverMouseClicked(evt);
            }
        });
        panel_server.add(tbl_mode_server, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 350, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panel_server.png"))); // NOI18N
        panel_server.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 770, -1));

        getContentPane().add(panel_server, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 99, 770, 570));

        menu_server.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu_server.png"))); // NOI18N
        menu_server.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_serverMouseClicked(evt);
            }
        });
        getContentPane().add(menu_server, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 230, 60));

        menu_client.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu_client.png"))); // NOI18N
        menu_client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_clientMouseClicked(evt);
            }
        });
        getContentPane().add(menu_client, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 158, 230, 60));

        menu_highlight_server.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/highlight menu.png"))); // NOI18N
        getContentPane().add(menu_highlight_server, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 230, 60));

        menu_highlight_client.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/highlight menu.png"))); // NOI18N
        getContentPane().add(menu_highlight_client, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 158, 230, 60));

        menu_highlight_about.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/highlight menu.png"))); // NOI18N
        getContentPane().add(menu_highlight_about, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 216, 230, 60));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/layout.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clear_panel() {
        panel_server.setVisible(false);
        panel_client.setVisible(false);
        panel_about.setVisible(false);
    }

    private void clear_highlight() {
        menu_highlight_client.setVisible(false);
        menu_highlight_server.setVisible(false);
        menu_highlight_about.setVisible(false);
    }
    private void menu_aboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_aboutMouseClicked
        clear_highlight();
        clear_panel();
        menu_highlight_about.setVisible(true);
        panel_about.setVisible(true);
    }//GEN-LAST:event_menu_aboutMouseClicked

    private void menu_clientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_clientMouseClicked
        clear_highlight();
        menu_highlight_client.setVisible(true);
        clear_panel();
        panel_client.setVisible(true);
    }//GEN-LAST:event_menu_clientMouseClicked

    private void menu_serverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_serverMouseClicked
        clear_highlight();
        menu_highlight_server.setVisible(true);
        clear_panel();
        panel_server.setVisible(true);
    }//GEN-LAST:event_menu_serverMouseClicked

    private void tbl_mode_serverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_mode_serverMouseClicked
        new ServerForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tbl_mode_serverMouseClicked

    private void tbl_mode_clientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_mode_clientMouseClicked
        new ClientForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_tbl_mode_clientMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel menu_about;
    private javax.swing.JLabel menu_client;
    private javax.swing.JLabel menu_highlight_about;
    private javax.swing.JLabel menu_highlight_client;
    private javax.swing.JLabel menu_highlight_server;
    private javax.swing.JLabel menu_server;
    private javax.swing.JLayeredPane panel_about;
    private javax.swing.JLayeredPane panel_client;
    private javax.swing.JLayeredPane panel_server;
    private javax.swing.JLabel tbl_mode_client;
    private javax.swing.JLabel tbl_mode_server;
    // End of variables declaration//GEN-END:variables

}
