/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Chat;

import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.UIManager;

/**
 *
 * @author Wildan
 */
public class ServerForm extends javax.swing.JFrame {

    public SocketServer server;
    //public SocketClient client;
    public Thread serverThread;
    public String username;
    public DefaultListModel model;
    public String filePath = "D:/Data.xml";
    public JFileChooser fileChooser;
    public ClientForm cf;

    /**
     * Creates new form ServerForm
     */
    public ServerForm() {
        initComponents();
        display.setEditable(false);
        this.setLocationRelativeTo(null);

    }

    public boolean isWin32() {
        return System.getProperty("os.name").startsWith("Windows");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_connect = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_connect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_connectMouseClicked(evt);
            }
        });
        getContentPane().add(btn_connect, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 590, 280, 60));

        jScrollPane1.setBorder(null);

        display.setColumns(20);
        display.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        display.setRows(5);
        display.setBorder(null);
        jScrollPane1.setViewportView(display);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 120, 910, 450));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/layout_server.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_connectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_connectMouseClicked
        server = new SocketServer(this); 
    }//GEN-LAST:event_btn_connectMouseClicked

    public void RetryStart(int port) {
        if (server != null) {
            server.stop();
        }
        server = new SocketServer(this, port);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ex) {
            System.out.println("Look & Feel Exception");
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_connect;
    public javax.swing.JTextArea display;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
